# ⚠️ EDIT "OPEN IN COLAB" BADGE PRIOR TO DOING ASSIGNMENT

<a target="_blank" href="https://colab.research.google.com/github/BenjaminHerrera/MAT422/blob/main/HW_1.4.ipynb">
    <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# HW 1.4
# Benjamin Herrera
# 15 SEP 2024

# ⚠️ Run these commands prior to running anything

In [94]:
!pip install scipy
!pip install matplotlib
!pip install numpy

## 📐 Singular Value Decomposition

In [95]:
# Imports
import numpy as np

# Let's assume some random 5x4 matrix
A = np.random.rand(5,4)

# Show the matrix 
print(A)

[[0.88735353 0.49742042 0.13919996 0.49907701]
 [0.6846934  0.00382974 0.08074103 0.364216  ]
 [0.62553704 0.49257638 0.62480823 0.42798695]
 [0.57327704 0.28111796 0.58368079 0.32001847]
 [0.4142691  0.04015631 0.74039113 0.14411758]]


In [96]:
# When we multiply the transpose of A against itself, we get a resulting matrix
#   that is orthogonally diagonalized
A_result = np.matmul(A.transpose(), A) 

# Show the matrix
print(A_result)

[[2.14776337 0.92992873 1.21097507 1.20311843]
 [0.92992873 0.57071307 0.57113043 0.55621239]
 [1.21097507 0.57113043 1.30514336 0.65978046]
 [1.20311843 0.55621239 0.65978046 0.68808569]]


In [97]:
# Now let's find the eigenvectors of A 
A_eigenvalues, A_eigenvectors = np.linalg.eig(A_result)

# Show the eigenvalues and eigen vectors
print("Eigenvalues:")
print(A_eigenvalues)
print()
print("Eigenvectors:")
print(A_eigenvectors)
print()

Eigenvalues:
[4.06754243 0.50018756 0.00417386 0.13980164]

Eigenvectors:
[[ 0.71056027  0.37322887  0.43224528  0.41105758]
 [ 0.33024291  0.14713122  0.19676355 -0.9113595 ]
 [ 0.47533853 -0.87849931 -0.04295501  0.02114481]
 [ 0.40012124  0.25940618 -0.87897838 -0.00290441]]



In [98]:
# Let's also get the orthonormal basis of the eigenvectors
Q, _ = np.linalg.qr(A_eigenvectors)

# Show the orthonormal basis 
print(Q)

[[-0.71056027 -0.37322887  0.43224528  0.41105758]
 [-0.33024291 -0.14713122  0.19676355 -0.9113595 ]
 [-0.47533853  0.87849931 -0.04295501  0.02114481]
 [-0.40012124 -0.25940618 -0.87897838 -0.00290441]]


If we conduct the following calculations:

$$||Av_i||^2 = (Av_i)^T Av_i = v_i^T A^T A v_i$$

We get:

In [99]:
# Calculate the norm
for i in range(len(A_eigenvectors)):
    print(A_eigenvectors[i].T @ (A_eigenvalues[i] * A_eigenvectors[i]))

4.067542428694026
0.5001875647833662
0.004173855226968785
0.13980163864480294


Which are the the eigenvalues of the matrix. This means that $||Av_i||^2$ are eigenvectors for $[i, n]$

In [100]:
# We define the singular values of A as the square root of the eigenvalues
A_singular_values = [np.sqrt(i) for i in A_eigenvalues]

# Show the singular values
print(A_singular_values)

[2.016814921774931, 0.7072393970809081, 0.06460538078959666, 0.3739005732073742]


In other words, this is just $\{||Av_1||, \dots, ||Av_n||\}$

In [101]:
# A cool thing is that the number of nonzero singular values equal to the 
#   dimensions of col(A)
count = 0
for i in A_singular_values:
    if i >= 0:
        count += 1
        
# Show the number of nonzero singular values
print(count)

# Show the dimension of col(A)
rank = np.linalg.matrix_rank(A)
col_space = Q[:, :rank]
print(col_space.shape[0])

4
4


In [102]:
# We can now conduct a SVD of A, simply with this line
U, E, V = np.linalg.svd(A, full_matrices=True)

# Show the m x m orthogonal matrix U
print("U")
print(U)
print()

# Show the m x n matrix E
diag_E = np.append(np.diag(E), [np.zeros(4)], axis=0)
m, n = A.shape
print("E")
print(np.append(np.diag(E), [np.zeros(4)] * (m - n), axis=0))
print()

# Show the n x n orthogonal matrix V
print("V")
print(V)
print()

U
[[-0.52590158 -0.58190851 -0.23290041  0.56916847  0.08133058]
 [-0.33314438 -0.39542447  0.74513809 -0.41633028  0.06397371]
 [-0.53321389  0.18654121 -0.480914   -0.55294787  0.37928315]
 [-0.44906315  0.24662602 -0.02443778 -0.05032498 -0.85696446]
 [-0.35562283  0.6398437   0.39831036  0.4409449   0.33324001]]

E
[[2.01681492 0.         0.         0.        ]
 [0.         0.7072394  0.         0.        ]
 [0.         0.         0.37390057 0.        ]
 [0.         0.         0.         0.06460538]
 [0.         0.         0.         0.        ]]

V
[[-0.71056027 -0.33024291 -0.47533853 -0.40012124]
 [-0.37322887 -0.14713122  0.87849931 -0.25940618]
 [ 0.41105758 -0.9113595   0.02114481 -0.00290441]
 [ 0.43224528  0.19676355 -0.04295501 -0.87897838]]



In [103]:
# We can now construct the original matrix as such
print("Reconstructed")
print(U @ diag_E @ V)
print()

# Show the original matrix
print("Original")
print(A)
print()

Reconstructed
[[0.88735353 0.49742042 0.13919996 0.49907701]
 [0.6846934  0.00382974 0.08074103 0.364216  ]
 [0.62553704 0.49257638 0.62480823 0.42798695]
 [0.57327704 0.28111796 0.58368079 0.32001847]
 [0.4142691  0.04015631 0.74039113 0.14411758]]

Original
[[0.88735353 0.49742042 0.13919996 0.49907701]
 [0.6846934  0.00382974 0.08074103 0.364216  ]
 [0.62553704 0.49257638 0.62480823 0.42798695]
 [0.57327704 0.28111796 0.58368079 0.32001847]
 [0.4142691  0.04015631 0.74039113 0.14411758]]



# ⛵ Low-Rank Matrix Approximations

Using the same information (code and all), let's define the induced norm. This defined as the distance between two different matrixes. Chapter 1.4.2 definitions this as below:

$$||A||_2 = \max_{0\neq x \isin \Reals^{m}} \frac{||Ax||}{||x||} = \max_{x \neq 0, ||x|| = 1} ||Ax|| = \max_{x \neq 0, ||X|| = 1} x^T A^T A x$$

In other words:

$$||A||_2 = \sqrt{\lambda_{max} A^T A}$$

With the previous definitions of the singular values, $m \times m$ U vectors, and the eigenvectors $v_j$, we can reconstruct $A$

In [104]:
# Let's define a new matrix in n x m format
A = np.random.rand(4,5)
A_result = A.transpose() @ A 
A_eigenvalues, A_eigenvectors = np.linalg.eig(A_result)
Q, _ = np.linalg.qr(A_eigenvectors)
A_singular_values = [np.sqrt(i) for i in A_eigenvalues]
U, E, V = np.linalg.svd(A, full_matrices=True)
n, m = A.shape

# Print A
print(A)


[[0.13764184 0.58794198 0.72148699 0.8350014  0.85421972]
 [0.11548941 0.24986147 0.23709128 0.73068796 0.51205903]
 [0.71816021 0.38687043 0.69335651 0.86855307 0.94293794]
 [0.91193655 0.43580569 0.28310736 0.1308815  0.24253488]]


In [105]:
# Build a reconstruction of A with singular values, m x m U vectors, and 
#   eigenvectors of A
A_reconstructed = np.zeros((n, m))
for j in range(len(E)):
    A_reconstructed += E[j] * np.outer(U[:, j], V[j, :])
    
# Print the resulting matrix
print(A_reconstructed)

[[0.13764184 0.58794198 0.72148699 0.8350014  0.85421972]
 [0.11548941 0.24986147 0.23709128 0.73068796 0.51205903]
 [0.71816021 0.38687043 0.69335651 0.86855307 0.94293794]
 [0.91193655 0.43580569 0.28310736 0.1308815  0.24253488]]


YAY! It's the same! A cool thing is that we can create a "resolution" of the reconstruction by specifying if we want all of the of terms or part of it. Below is an example with half of the terms:

In [106]:
# Build a reconstruction of A with singular values, m x m U vectors, and 
#   eigenvectors of A. 
# But this time, with half of the terms
k = int(len(E) / 2)
A_reconstructed_k = np.zeros((n, m))
for j in range(k):
    A_reconstructed_k += E[j] * np.outer(U[:, j], V[j, :])
    
# Print the resulting matrix
print(A_reconstructed_k)

[[0.20249784 0.43829494 0.62783005 0.93322483 0.87657095]
 [0.07032496 0.26178826 0.38799984 0.59705256 0.55071557]
 [0.67587424 0.55566654 0.68828551 0.85486065 0.886516  ]
 [0.93192    0.34500337 0.29574798 0.12955331 0.27568101]]


Using this idea, we can show that:

$$||A - A_k||_2^2 = \sigma_{k+1}^2$$ 

In [107]:
# Demonstrate the above notion
A_difference = A_reconstructed - A_reconstructed_k
A_induced_norm = np.linalg.norm(A_difference, ord=2) # induced norm

# Show similarities
print(E[k] ** 2)
print(A_induced_norm ** 2)

0.09123701062262397
0.09123701062262397
