# ⚠️ EDIT "OPEN IN COLAB" BADGE PRIOR TO DOING ASSIGNMENT

<a target="_blank" href="https://colab.research.google.com/github/BenjaminHerrera/MAT422/blob/main/HW_1.4.ipynb">
    <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# HW 1.4
# Benjamin Herrera
# 15 SEP 2024

# ⚠️ Run these commands prior to running anything

In [5]:
!pip install scipy
!pip install matplotlib
!pip install numpy

## 📐 Singular Value Decomposition

In [6]:
# Imports
import numpy as np

# Let's assume some random 5x4 matrix
A = np.random.rand(5,4)

# Show the matrix 
print(A)

[[0.73603602 0.40202111 0.84023413 0.6033866 ]
 [0.94680652 0.15140284 0.16830036 0.41026334]
 [0.88225911 0.11779956 0.66367753 0.39480194]
 [0.72786678 0.58474827 0.6030089  0.98165908]
 [0.92598325 0.4581627  0.42531514 0.25542223]]


In [7]:
# When we multiply the transpose of A against itself, we get a resulting matrix
#   that is orthogonally diagonalized
A_result = np.matmul(A.transpose(), A) 

# Show the matrix
print(A_result)

[[3.60380777 1.39305077 2.19607084 2.13190563]
 [1.39305077 0.75026413 0.98892587 1.04224507]
 [2.19607084 0.98892587 1.71929897 1.53863877]
 [2.13190563 1.04224507 1.53863877 1.71715505]]


In [8]:
# Now let's find the eigenvectors of A 
A_eigenvalues, A_eigenvectors = np.linalg.eig(A_result)

# Show the eigenvalues and eigen vectors
print("Eigenvalues:")
print(A_eigenvalues)
print()
print("Eigenvectors:")
print(A_eigenvectors)
print()

Eigenvalues:
[7.12280662 0.39930751 0.1846505  0.08376129]

Eigenvectors:
[[-0.69086219 -0.70866905  0.13742889  0.04013617]
 [-0.29933092  0.29730752  0.28017723 -0.86227023]
 [-0.46746492  0.29360447 -0.83379733 -0.00741474]
 [-0.46323534  0.56850051  0.45540755  0.5048011 ]]



In [9]:
# Let's also get the orthonormal basis of the eigenvectors
Q, _ = np.linalg.qr(A_eigenvectors)

# Show the orthonormal basis 
print(Q)

[[-0.69086219  0.70866905  0.13742889  0.04013617]
 [-0.29933092 -0.29730752  0.28017723 -0.86227023]
 [-0.46746492 -0.29360447 -0.83379733 -0.00741474]
 [-0.46323534 -0.56850051  0.45540755  0.5048011 ]]


If we conduct the following calculations:

$$||Av_i||^2 = (Av_i)^T Av_i = v_i^T A^T A v_i$$

We get:

In [10]:
# Calculate the norm
for i in range(len(A_eigenvectors)):
    print(A_eigenvectors[i].T @ (A_eigenvalues[i] * A_eigenvectors[i]))

7.1228066187857735
0.3993075068665358
0.18465049921850626
0.08376128747760704


Which are the the eigenvalues of the matrix. This means that $||Av_i||^2$ are eigenvectors for $[i, n]$

In [11]:
# We define the singular values of A as the square root of the eigenvalues
A_singular_values = [np.sqrt(i) for i in A_eigenvalues]

# Show the singular values
print(A_singular_values)

[2.6688586734381006, 0.6319078309900394, 0.42970978487638156, 0.2894154237037255]


In other words, this is just $\{||Av_1||, \dots, ||Av_n||\}$

In [12]:
# A cool thing is that the number of nonzero singular values equal to the 
#   dimensions of col(A)
count = 0
for i in A_singular_values:
    if i >= 0:
        count += 1
        
# Show the number of nonzero singular values
print(count)

# Show the dimension of col(A)
rank = np.linalg.matrix_rank(A)
col_space = Q[:, :rank]
print(col_space.shape[0])

4
4


In [13]:
# We can now conduct a SVD of A, simply with this line
U, E, V = np.linalg.svd(A, full_matrices=True)

# Show the m x m orthogonal matrix U
print("U")
print(U)
print()

# Show the m x n matrix E
diag_E = np.append(np.diag(E), [np.zeros(4)], axis=0)
m, n = A.shape
print("E")
print(np.append(np.diag(E), [np.zeros(4)] * (m - n), axis=0))
print()

# Show the n x n orthogonal matrix V
print("V")
print(V)
print()

U
[[-0.4875218   0.29694212 -0.49337576  0.06478251 -0.65309376]
 [-0.36276007 -0.54329223  0.50975527 -0.39149436 -0.40015048]
 [-0.42636678 -0.27045594 -0.51040058 -0.44299959  0.53694279]
 [-0.53000692  0.62216859  0.48435206 -0.05554021  0.30711117]
 [-0.40991664 -0.39549811  0.04030206  0.80199877  0.17528063]]

E
[[2.66885867 0.         0.         0.        ]
 [0.         0.63190783 0.         0.        ]
 [0.         0.         0.42970978 0.        ]
 [0.         0.         0.         0.28941542]
 [0.         0.         0.         0.        ]]

V
[[-0.69086219 -0.29933092 -0.46746492 -0.46323534]
 [-0.70866905  0.29730752  0.29360447  0.56850051]
 [ 0.13742889  0.28017723 -0.83379733  0.45540755]
 [-0.04013617  0.86227023  0.00741474 -0.5048011 ]]



In [14]:
# We can now construct the original matrix as such
print("Reconstructed")
print(U @ diag_E @ V)
print()

# Show the original matrix
print("Original")
print(A)
print()

Reconstructed
[[0.73603602 0.40202111 0.84023413 0.6033866 ]
 [0.94680652 0.15140284 0.16830036 0.41026334]
 [0.88225911 0.11779956 0.66367753 0.39480194]
 [0.72786678 0.58474827 0.6030089  0.98165908]
 [0.92598325 0.4581627  0.42531514 0.25542223]]

Original
[[0.73603602 0.40202111 0.84023413 0.6033866 ]
 [0.94680652 0.15140284 0.16830036 0.41026334]
 [0.88225911 0.11779956 0.66367753 0.39480194]
 [0.72786678 0.58474827 0.6030089  0.98165908]
 [0.92598325 0.4581627  0.42531514 0.25542223]]



# ⛵ Low-Rank Matrix Approximations

Using the same information (code and all), let's define the induced norm. This defined as the distance between two different matrixes. Chapter 1.4.2 definitions this as below:

$$||A||_2 = \max_{0\neq x \isin \Reals^{m}} \frac{||Ax||}{||x||} = \max_{x \neq 0, ||x|| = 1} ||Ax|| = \max_{x \neq 0, ||X|| = 1} x^T A^T A x$$

In other words:

$$||A||_2 = \sqrt{\lambda_{max} A^T A}$$

With the previous definitions of the singular values, $m \times m$ U vectors, and the eigenvectors $v_j$, we can reconstruct $A$

In [15]:
# Let's define a new matrix in n x m format
A = np.random.rand(4,5)
A_result = A.transpose() @ A 
A_eigenvalues, A_eigenvectors = np.linalg.eig(A_result)
Q, _ = np.linalg.qr(A_eigenvectors)
A_singular_values = [np.sqrt(i) for i in A_eigenvalues]
U, E, V = np.linalg.svd(A, full_matrices=True)
n, m = A.shape

# Print A
print(A)


[[0.61035302 0.43415396 0.85245542 0.93367083 0.47768664]
 [0.12279571 0.77095948 0.89056949 0.89425462 0.51393668]
 [0.14078068 0.30877115 0.43290718 0.38346626 0.00283509]
 [0.17595007 0.25597648 0.20614041 0.49186853 0.97695307]]


In [16]:
# Build a reconstruction of A with singular values, m x m U vectors, and 
#   eigenvectors of A
A_reconstructed = np.zeros((n, m))
for j in range(len(E)):
    A_reconstructed += E[j] * np.outer(U[:, j], V[j, :])
    
# Print the resulting matrix
print(A_reconstructed)

[[0.61035302 0.43415396 0.85245542 0.93367083 0.47768664]
 [0.12279571 0.77095948 0.89056949 0.89425462 0.51393668]
 [0.14078068 0.30877115 0.43290718 0.38346626 0.00283509]
 [0.17595007 0.25597648 0.20614041 0.49186853 0.97695307]]


YAY! It's the same! A cool thing is that we can create a "resolution" of the reconstruction by specifying if we want all of the of terms or part of it. Below is an example with half of the terms:

In [17]:
# Build a reconstruction of A with singular values, m x m U vectors, and 
#   eigenvectors of A. 
# But this time, with half of the terms
k = int(len(E) / 2)
A_reconstructed_k = np.zeros((n, m))
for j in range(k):
    A_reconstructed_k += E[j] * np.outer(U[:, j], V[j, :])
    
# Print the resulting matrix
print(A_reconstructed_k)

[[0.35528545 0.60540485 0.857916   0.9036629  0.49657213]
 [0.36272779 0.61919077 0.87973855 0.92218113 0.49519425]
 [0.15452284 0.28321997 0.44258686 0.38560981 0.00352989]
 [0.18393282 0.24595117 0.20882012 0.49295825 0.9768514 ]]


Using this idea, we can show that:

$$||A - A_k||_2^2 = \sigma_{k+1}^2$$ 

In [18]:
# Demonstrate the above notion
A_difference = A_reconstructed - A_reconstructed_k
A_induced_norm = np.linalg.norm(A_difference, ord=2) # induced norm

# Show similarities
print(E[k] ** 2)
print(A_induced_norm ** 2)

0.1782551143511746
0.17825511435117447


## ⚙️ Principal Component Analysis

In [42]:
# To demonstrate the idea of principal component analysis, let's define a
#   p x N matrix 
p = 4
N = 5
X = np.random.rand(p, N)

# Show the content of X
print(X)

[[0.35584265 0.09028438 0.75396553 0.30165654 0.27934636]
 [0.97983281 0.82202976 0.63337227 0.08999584 0.65890704]
 [0.52328962 0.37040286 0.27416364 0.56132893 0.58220969]
 [0.45954396 0.56458512 0.60519253 0.97137665 0.65447334]]


In [43]:
# Let's get an "average" of all of the vectors
M = (1/N) * A.sum(axis=1)

# Show the average of the vectors
print(M)

[0.66166397 0.6385032  0.25375207 0.42137771]


In [45]:
# Now we subtract all of the original vectors in X with M
B = np.vstack([i - M for i in X.T])

# Show B 
print(B)

[[-0.30582133  0.34132961  0.26953755  0.03816625]
 [-0.57137959  0.18352656  0.11665079  0.14320741]
 [ 0.09230155 -0.00513092  0.02041157  0.18381481]
 [-0.36000743 -0.54850736  0.30757686  0.54999893]
 [-0.38231761  0.02040384  0.32845762  0.23309563]]


In [48]:
# From this, we can make a covariance matrix of size p x p 
S = (1/(N-1)) * B @ B.T

# Show the covariance matrix
print(S)

[[ 0.07103493  0.06857264 -0.00436548  0.00669276  0.05532834]
 [ 0.06857264  0.0985681  -0.00624405  0.05491956  0.07347225]
 [-0.00436548 -0.00624405  0.01068761  0.0192403   0.00353939]
 [ 0.00669276  0.05491956  0.0192403   0.20689201  0.08891846]
 [ 0.05532834  0.07347225  0.00353939  0.08891846  0.07720026]]


In PCA, we want to find some value k to find the top k number of components. This is done via:

$$\max \frac{1}{N}\sum_{i=1}^{N}\sum_{j=1}^{k}<X_i \cdot v_j>^2$$